/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionRequest
 */
export interface CompletionRequest {
    /**
     * 
     * @type {string}
     * @memberof CompletionRequest
     */
    prompt: string;
}

/**
 * Check if a given object implements the CompletionRequest interface.
 */
export function instanceOfCompletionRequest(value: object): value is CompletionRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function CompletionRequestFromJSON(json: any): CompletionRequest {
    return CompletionRequestFromJSONTyped(json, false);
}

export function CompletionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
    };
}

export function CompletionRequestToJSON(json: any): CompletionRequest {
    return CompletionRequestToJSONTyped(json, false);
}

export function CompletionRequestToJSONTyped(value?: CompletionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
    };
}

