/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Document details for update.
 * @export
 * @interface DocumentUpdate
 */
export interface DocumentUpdate {
    /**
     * 
     * @type {string}
     * @memberof DocumentUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentUpdate
     */
    content?: string | null;
}

/**
 * Check if a given object implements the DocumentUpdate interface.
 */
export function instanceOfDocumentUpdate(value: object): value is DocumentUpdate {
    return true;
}

export function DocumentUpdateFromJSON(json: any): DocumentUpdate {
    return DocumentUpdateFromJSONTyped(json, false);
}

export function DocumentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function DocumentUpdateToJSON(json: any): DocumentUpdate {
    return DocumentUpdateToJSONTyped(json, false);
}

export function DocumentUpdateToJSONTyped(value?: DocumentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

