/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentMetas } from './DocumentMetas';
import {
    DocumentMetasFromJSON,
    DocumentMetasFromJSONTyped,
    DocumentMetasToJSON,
    DocumentMetasToJSONTyped,
} from './DocumentMetas';

/**
 * List of document metadata.
 * @export
 * @interface DocumentsMetas
 */
export interface DocumentsMetas {
    /**
     * 
     * @type {Array<DocumentMetas>}
     * @memberof DocumentsMetas
     */
    items: Array<DocumentMetas>;
}

/**
 * Check if a given object implements the DocumentsMetas interface.
 */
export function instanceOfDocumentsMetas(value: object): value is DocumentsMetas {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function DocumentsMetasFromJSON(json: any): DocumentsMetas {
    return DocumentsMetasFromJSONTyped(json, false);
}

export function DocumentsMetasFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsMetas {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DocumentMetasFromJSON)),
    };
}

export function DocumentsMetasToJSON(json: any): DocumentsMetas {
    return DocumentsMetasToJSONTyped(json, false);
}

export function DocumentsMetasToJSONTyped(value?: DocumentsMetas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DocumentMetasToJSON)),
    };
}

