/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Document details for creation.
 * @export
 * @interface DocumentCreate
 */
export interface DocumentCreate {
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCreate
     */
    content?: string | null;
}

/**
 * Check if a given object implements the DocumentCreate interface.
 */
export function instanceOfDocumentCreate(value: object): value is DocumentCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DocumentCreateFromJSON(json: any): DocumentCreate {
    return DocumentCreateFromJSONTyped(json, false);
}

export function DocumentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function DocumentCreateToJSON(json: any): DocumentCreate {
    return DocumentCreateToJSONTyped(json, false);
}

export function DocumentCreateToJSONTyped(value?: DocumentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

