/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Document metadata.
 * @export
 * @interface DocumentMetas
 */
export interface DocumentMetas {
    /**
     * 
     * @type {string}
     * @memberof DocumentMetas
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentMetas
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentMetas
     */
    userId: number;
}

/**
 * Check if a given object implements the DocumentMetas interface.
 */
export function instanceOfDocumentMetas(value: object): value is DocumentMetas {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function DocumentMetasFromJSON(json: any): DocumentMetas {
    return DocumentMetasFromJSONTyped(json, false);
}

export function DocumentMetasFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentMetas {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'uuid': json['uuid'],
        'userId': json['user_id'],
    };
}

export function DocumentMetasToJSON(json: any): DocumentMetas {
    return DocumentMetasToJSONTyped(json, false);
}

export function DocumentMetasToJSONTyped(value?: DocumentMetas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'uuid': value['uuid'],
        'user_id': value['userId'],
    };
}

