/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessagePublic
 */
export interface MessagePublic {
    /**
     * 
     * @type {string}
     * @memberof MessagePublic
     */
    message: string;
}

/**
 * Check if a given object implements the MessagePublic interface.
 */
export function instanceOfMessagePublic(value: object): value is MessagePublic {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MessagePublicFromJSON(json: any): MessagePublic {
    return MessagePublicFromJSONTyped(json, false);
}

export function MessagePublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagePublic {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function MessagePublicToJSON(json: any): MessagePublic {
    return MessagePublicToJSONTyped(json, false);
}

export function MessagePublicToJSONTyped(value?: MessagePublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

